//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GG_WebStore.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Service2")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GG_WebStore.ServiceReference1.Cust_addr[] Cust_addrsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GG_WebStore.ServiceReference1.Invoice[] InvoicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UserRegDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GG_WebStore.ServiceReference1.Cust_addr[] Cust_addrs {
            get {
                return this.Cust_addrsField;
            }
            set {
                if ((object.ReferenceEquals(this.Cust_addrsField, value) != true)) {
                    this.Cust_addrsField = value;
                    this.RaisePropertyChanged("Cust_addrs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GG_WebStore.ServiceReference1.Invoice[] Invoices {
            get {
                return this.InvoicesField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoicesField, value) != true)) {
                    this.InvoicesField = value;
                    this.RaisePropertyChanged("Invoices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserEmail {
            get {
                return this.UserEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.UserEmailField, value) != true)) {
                    this.UserEmailField = value;
                    this.RaisePropertyChanged("UserEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPass {
            get {
                return this.UserPassField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPassField, value) != true)) {
                    this.UserPassField = value;
                    this.RaisePropertyChanged("UserPass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UserRegDate {
            get {
                return this.UserRegDateField;
            }
            set {
                if ((this.UserRegDateField.Equals(value) != true)) {
                    this.UserRegDateField = value;
                    this.RaisePropertyChanged("UserRegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cust_addr", Namespace="http://schemas.datacontract.org/2004/07/Service2")]
    [System.SerializableAttribute()]
    public partial class Cust_addr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GG_WebStore.ServiceReference1.Address AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddressIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GG_WebStore.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GG_WebStore.ServiceReference1.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressId {
            get {
                return this.AddressIdField;
            }
            set {
                if ((this.AddressIdField.Equals(value) != true)) {
                    this.AddressIdField = value;
                    this.RaisePropertyChanged("AddressId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GG_WebStore.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoice", Namespace="http://schemas.datacontract.org/2004/07/Service2")]
    [System.SerializableAttribute()]
    public partial class Invoice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CheckedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GG_WebStore.ServiceReference1.InvoiceLine[] InvoiceLinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GG_WebStore.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Checked {
            get {
                return this.CheckedField;
            }
            set {
                if ((this.CheckedField.Equals(value) != true)) {
                    this.CheckedField = value;
                    this.RaisePropertyChanged("Checked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceId {
            get {
                return this.InvoiceIdField;
            }
            set {
                if ((this.InvoiceIdField.Equals(value) != true)) {
                    this.InvoiceIdField = value;
                    this.RaisePropertyChanged("InvoiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GG_WebStore.ServiceReference1.InvoiceLine[] InvoiceLines {
            get {
                return this.InvoiceLinesField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceLinesField, value) != true)) {
                    this.InvoiceLinesField = value;
                    this.RaisePropertyChanged("InvoiceLines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GG_WebStore.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/Service2")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddressIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GG_WebStore.ServiceReference1.Cust_addr[] Cust_addrsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressId {
            get {
                return this.AddressIdField;
            }
            set {
                if ((this.AddressIdField.Equals(value) != true)) {
                    this.AddressIdField = value;
                    this.RaisePropertyChanged("AddressId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GG_WebStore.ServiceReference1.Cust_addr[] Cust_addrs {
            get {
                return this.Cust_addrsField;
            }
            set {
                if ((object.ReferenceEquals(this.Cust_addrsField, value) != true)) {
                    this.Cust_addrsField = value;
                    this.RaisePropertyChanged("Cust_addrs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceLine", Namespace="http://schemas.datacontract.org/2004/07/Service2")]
    [System.SerializableAttribute()]
    public partial class InvoiceLine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GG_WebStore.ServiceReference1.Invoice InvoiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GG_WebStore.ServiceReference1.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GG_WebStore.ServiceReference1.Invoice Invoice {
            get {
                return this.InvoiceField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceField, value) != true)) {
                    this.InvoiceField = value;
                    this.RaisePropertyChanged("Invoice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceId {
            get {
                return this.InvoiceIdField;
            }
            set {
                if ((this.InvoiceIdField.Equals(value) != true)) {
                    this.InvoiceIdField = value;
                    this.RaisePropertyChanged("InvoiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GG_WebStore.ServiceReference1.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/Service2")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GG_WebStore.ServiceReference1.Brand BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BrandIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GG_WebStore.ServiceReference1.Category CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GG_WebStore.ServiceReference1.InvoiceLine[] InvoiceLinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProDescrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ProPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProStockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GG_WebStore.ServiceReference1.Brand Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BrandId {
            get {
                return this.BrandIdField;
            }
            set {
                if ((this.BrandIdField.Equals(value) != true)) {
                    this.BrandIdField = value;
                    this.RaisePropertyChanged("BrandId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GG_WebStore.ServiceReference1.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GG_WebStore.ServiceReference1.InvoiceLine[] InvoiceLines {
            get {
                return this.InvoiceLinesField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceLinesField, value) != true)) {
                    this.InvoiceLinesField = value;
                    this.RaisePropertyChanged("InvoiceLines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProDescr {
            get {
                return this.ProDescrField;
            }
            set {
                if ((object.ReferenceEquals(this.ProDescrField, value) != true)) {
                    this.ProDescrField = value;
                    this.RaisePropertyChanged("ProDescr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProImage {
            get {
                return this.ProImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ProImageField, value) != true)) {
                    this.ProImageField = value;
                    this.RaisePropertyChanged("ProImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProName {
            get {
                return this.ProNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProNameField, value) != true)) {
                    this.ProNameField = value;
                    this.RaisePropertyChanged("ProName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ProPrice {
            get {
                return this.ProPriceField;
            }
            set {
                if ((this.ProPriceField.Equals(value) != true)) {
                    this.ProPriceField = value;
                    this.RaisePropertyChanged("ProPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProStock {
            get {
                return this.ProStockField;
            }
            set {
                if ((this.ProStockField.Equals(value) != true)) {
                    this.ProStockField = value;
                    this.RaisePropertyChanged("ProStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Brand", Namespace="http://schemas.datacontract.org/2004/07/Service2")]
    [System.SerializableAttribute()]
    public partial class Brand : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BrandIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GG_WebStore.ServiceReference1.Product[] ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BrandId {
            get {
                return this.BrandIdField;
            }
            set {
                if ((this.BrandIdField.Equals(value) != true)) {
                    this.BrandIdField = value;
                    this.RaisePropertyChanged("BrandId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandName {
            get {
                return this.BrandNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandNameField, value) != true)) {
                    this.BrandNameField = value;
                    this.RaisePropertyChanged("BrandName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GG_WebStore.ServiceReference1.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/Service2")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GG_WebStore.ServiceReference1.Product[] ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GG_WebStore.ServiceReference1.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceLineStruct", Namespace="http://schemas.datacontract.org/2004/07/Service2")]
    [System.SerializableAttribute()]
    public partial struct InvoiceLineStruct : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GG_WebStore.ServiceReference1.InvoiceLine[] ILS_InvoiceLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GG_WebStore.ServiceReference1.Product[] ILS_ProdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GG_WebStore.ServiceReference1.InvoiceLine[] ILS_InvoiceLine {
            get {
                return this.ILS_InvoiceLineField;
            }
            set {
                if ((object.ReferenceEquals(this.ILS_InvoiceLineField, value) != true)) {
                    this.ILS_InvoiceLineField = value;
                    this.RaisePropertyChanged("ILS_InvoiceLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GG_WebStore.ServiceReference1.Product[] ILS_Prod {
            get {
                return this.ILS_ProdField;
            }
            set {
                if ((object.ReferenceEquals(this.ILS_ProdField, value) != true)) {
                    this.ILS_ProdField = value;
                    this.RaisePropertyChanged("ILS_Prod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserLogin", ReplyAction="http://tempuri.org/IService1/UserLoginResponse")]
        char UserLogin(string userEmail, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserLogin", ReplyAction="http://tempuri.org/IService1/UserLoginResponse")]
        System.Threading.Tasks.Task<char> UserLoginAsync(string userEmail, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserRegister", ReplyAction="http://tempuri.org/IService1/UserRegisterResponse")]
        bool UserRegister(GG_WebStore.ServiceReference1.User newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserRegister", ReplyAction="http://tempuri.org/IService1/UserRegisterResponse")]
        System.Threading.Tasks.Task<bool> UserRegisterAsync(GG_WebStore.ServiceReference1.User newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCarts", ReplyAction="http://tempuri.org/IService1/getCartsResponse")]
        GG_WebStore.ServiceReference1.InvoiceLine[] getCarts(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCarts", ReplyAction="http://tempuri.org/IService1/getCartsResponse")]
        System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.InvoiceLine[]> getCartsAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addProductToCart", ReplyAction="http://tempuri.org/IService1/addProductToCartResponse")]
        bool addProductToCart(int userId, int proId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addProductToCart", ReplyAction="http://tempuri.org/IService1/addProductToCartResponse")]
        System.Threading.Tasks.Task<bool> addProductToCartAsync(int userId, int proId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteFromCart", ReplyAction="http://tempuri.org/IService1/deleteFromCartResponse")]
        bool deleteFromCart(int userId, int proId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteFromCart", ReplyAction="http://tempuri.org/IService1/deleteFromCartResponse")]
        System.Threading.Tasks.Task<bool> deleteFromCartAsync(int userId, int proId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllInvoices", ReplyAction="http://tempuri.org/IService1/getAllInvoicesResponse")]
        GG_WebStore.ServiceReference1.Invoice[] getAllInvoices(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllInvoices", ReplyAction="http://tempuri.org/IService1/getAllInvoicesResponse")]
        System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.Invoice[]> getAllInvoicesAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getNumItems", ReplyAction="http://tempuri.org/IService1/getNumItemsResponse")]
        int getNumItems(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getNumItems", ReplyAction="http://tempuri.org/IService1/getNumItemsResponse")]
        System.Threading.Tasks.Task<int> getNumItemsAsync(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getInvoiceTotalPrice", ReplyAction="http://tempuri.org/IService1/getInvoiceTotalPriceResponse")]
        decimal getInvoiceTotalPrice(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getInvoiceTotalPrice", ReplyAction="http://tempuri.org/IService1/getInvoiceTotalPriceResponse")]
        System.Threading.Tasks.Task<decimal> getInvoiceTotalPriceAsync(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUncheackedInvoice", ReplyAction="http://tempuri.org/IService1/getUncheackedInvoiceResponse")]
        int getUncheackedInvoice(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUncheackedInvoice", ReplyAction="http://tempuri.org/IService1/getUncheackedInvoiceResponse")]
        System.Threading.Tasks.Task<int> getUncheackedInvoiceAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkout", ReplyAction="http://tempuri.org/IService1/checkoutResponse")]
        bool checkout(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkout", ReplyAction="http://tempuri.org/IService1/checkoutResponse")]
        System.Threading.Tasks.Task<bool> checkoutAsync(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProductsOnInvoice", ReplyAction="http://tempuri.org/IService1/getProductsOnInvoiceResponse")]
        GG_WebStore.ServiceReference1.InvoiceLine[] getProductsOnInvoice(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProductsOnInvoice", ReplyAction="http://tempuri.org/IService1/getProductsOnInvoiceResponse")]
        System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.InvoiceLine[]> getProductsOnInvoiceAsync(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateCart", ReplyAction="http://tempuri.org/IService1/updateCartResponse")]
        bool updateCart(int invoiceId, int productId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateCart", ReplyAction="http://tempuri.org/IService1/updateCartResponse")]
        System.Threading.Tasks.Task<bool> updateCartAsync(int invoiceId, int productId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProducts", ReplyAction="http://tempuri.org/IService1/getAllProductsResponse")]
        GG_WebStore.ServiceReference1.Product[] getAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProducts", ReplyAction="http://tempuri.org/IService1/getAllProductsResponse")]
        System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.Product[]> getAllProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSingleProduct", ReplyAction="http://tempuri.org/IService1/GetSingleProductResponse")]
        GG_WebStore.ServiceReference1.Product GetSingleProduct(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSingleProduct", ReplyAction="http://tempuri.org/IService1/GetSingleProductResponse")]
        System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.Product> GetSingleProductAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUser", ReplyAction="http://tempuri.org/IService1/getUserResponse")]
        GG_WebStore.ServiceReference1.User getUser(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUser", ReplyAction="http://tempuri.org/IService1/getUserResponse")]
        System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.User> getUserAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getNewArrivalProducts", ReplyAction="http://tempuri.org/IService1/getNewArrivalProductsResponse")]
        GG_WebStore.ServiceReference1.Product[] getNewArrivalProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getNewArrivalProducts", ReplyAction="http://tempuri.org/IService1/getNewArrivalProductsResponse")]
        System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.Product[]> getNewArrivalProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getFeaturedProducts", ReplyAction="http://tempuri.org/IService1/getFeaturedProductsResponse")]
        GG_WebStore.ServiceReference1.Product[] getFeaturedProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getFeaturedProducts", ReplyAction="http://tempuri.org/IService1/getFeaturedProductsResponse")]
        System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.Product[]> getFeaturedProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/countProducts", ReplyAction="http://tempuri.org/IService1/countProductsResponse")]
        int countProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/countProducts", ReplyAction="http://tempuri.org/IService1/countProductsResponse")]
        System.Threading.Tasks.Task<int> countProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GenerateUserRegReport", ReplyAction="http://tempuri.org/IService1/GenerateUserRegReportResponse")]
        int GenerateUserRegReport(System.DateTime regfordate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GenerateUserRegReport", ReplyAction="http://tempuri.org/IService1/GenerateUserRegReportResponse")]
        System.Threading.Tasks.Task<int> GenerateUserRegReportAsync(System.DateTime regfordate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProductById", ReplyAction="http://tempuri.org/IService1/DeleteProductByIdResponse")]
        bool DeleteProductById(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProductById", ReplyAction="http://tempuri.org/IService1/DeleteProductByIdResponse")]
        System.Threading.Tasks.Task<bool> DeleteProductByIdAsync(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditProduct", ReplyAction="http://tempuri.org/IService1/EditProductResponse")]
        bool EditProduct(int productId, string productName, int prodcuctActive, decimal productPrice, string productImage, decimal productDiscount, int CategoryId, string productDescri, int brandId, int productStock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditProduct", ReplyAction="http://tempuri.org/IService1/EditProductResponse")]
        System.Threading.Tasks.Task<bool> EditProductAsync(int productId, string productName, int prodcuctActive, decimal productPrice, string productImage, decimal productDiscount, int CategoryId, string productDescri, int brandId, int productStock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProduct", ReplyAction="http://tempuri.org/IService1/AddProductResponse")]
        bool AddProduct(string productName, int prodcuctActive, decimal productPrice, string productImage, decimal productDiscount, int CategoryId, string productDescri, int brandId, int productStock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProduct", ReplyAction="http://tempuri.org/IService1/AddProductResponse")]
        System.Threading.Tasks.Task<bool> AddProductAsync(string productName, int prodcuctActive, decimal productPrice, string productImage, decimal productDiscount, int CategoryId, string productDescri, int brandId, int productStock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductsByPriceRange", ReplyAction="http://tempuri.org/IService1/GetProductsByPriceRangeResponse")]
        GG_WebStore.ServiceReference1.Product[] GetProductsByPriceRange(decimal minimumPrice, decimal maximumPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductsByPriceRange", ReplyAction="http://tempuri.org/IService1/GetProductsByPriceRangeResponse")]
        System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.Product[]> GetProductsByPriceRangeAsync(decimal minimumPrice, decimal maximumPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductByBrand", ReplyAction="http://tempuri.org/IService1/GetProductByBrandResponse")]
        GG_WebStore.ServiceReference1.Product[] GetProductByBrand(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductByBrand", ReplyAction="http://tempuri.org/IService1/GetProductByBrandResponse")]
        System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.Product[]> GetProductByBrandAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductByCategory", ReplyAction="http://tempuri.org/IService1/GetProductByCategoryResponse")]
        GG_WebStore.ServiceReference1.Product[] GetProductByCategory(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductByCategory", ReplyAction="http://tempuri.org/IService1/GetProductByCategoryResponse")]
        System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.Product[]> GetProductByCategoryAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInvoiceLines", ReplyAction="http://tempuri.org/IService1/GetInvoiceLinesResponse")]
        GG_WebStore.ServiceReference1.InvoiceLineStruct[] GetInvoiceLines(int InvoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInvoiceLines", ReplyAction="http://tempuri.org/IService1/GetInvoiceLinesResponse")]
        System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.InvoiceLineStruct[]> GetInvoiceLinesAsync(int InvoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInvoices", ReplyAction="http://tempuri.org/IService1/GetInvoicesResponse")]
        GG_WebStore.ServiceReference1.Invoice[] GetInvoices(int UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInvoices", ReplyAction="http://tempuri.org/IService1/GetInvoicesResponse")]
        System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.Invoice[]> GetInvoicesAsync(int UserId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : GG_WebStore.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<GG_WebStore.ServiceReference1.IService1>, GG_WebStore.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public char UserLogin(string userEmail, string userPassword) {
            return base.Channel.UserLogin(userEmail, userPassword);
        }
        
        public System.Threading.Tasks.Task<char> UserLoginAsync(string userEmail, string userPassword) {
            return base.Channel.UserLoginAsync(userEmail, userPassword);
        }
        
        public bool UserRegister(GG_WebStore.ServiceReference1.User newUser) {
            return base.Channel.UserRegister(newUser);
        }
        
        public System.Threading.Tasks.Task<bool> UserRegisterAsync(GG_WebStore.ServiceReference1.User newUser) {
            return base.Channel.UserRegisterAsync(newUser);
        }
        
        public GG_WebStore.ServiceReference1.InvoiceLine[] getCarts(int userId) {
            return base.Channel.getCarts(userId);
        }
        
        public System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.InvoiceLine[]> getCartsAsync(int userId) {
            return base.Channel.getCartsAsync(userId);
        }
        
        public bool addProductToCart(int userId, int proId, int quantity) {
            return base.Channel.addProductToCart(userId, proId, quantity);
        }
        
        public System.Threading.Tasks.Task<bool> addProductToCartAsync(int userId, int proId, int quantity) {
            return base.Channel.addProductToCartAsync(userId, proId, quantity);
        }
        
        public bool deleteFromCart(int userId, int proId) {
            return base.Channel.deleteFromCart(userId, proId);
        }
        
        public System.Threading.Tasks.Task<bool> deleteFromCartAsync(int userId, int proId) {
            return base.Channel.deleteFromCartAsync(userId, proId);
        }
        
        public GG_WebStore.ServiceReference1.Invoice[] getAllInvoices(int userId) {
            return base.Channel.getAllInvoices(userId);
        }
        
        public System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.Invoice[]> getAllInvoicesAsync(int userId) {
            return base.Channel.getAllInvoicesAsync(userId);
        }
        
        public int getNumItems(int invoiceId) {
            return base.Channel.getNumItems(invoiceId);
        }
        
        public System.Threading.Tasks.Task<int> getNumItemsAsync(int invoiceId) {
            return base.Channel.getNumItemsAsync(invoiceId);
        }
        
        public decimal getInvoiceTotalPrice(int invoiceId) {
            return base.Channel.getInvoiceTotalPrice(invoiceId);
        }
        
        public System.Threading.Tasks.Task<decimal> getInvoiceTotalPriceAsync(int invoiceId) {
            return base.Channel.getInvoiceTotalPriceAsync(invoiceId);
        }
        
        public int getUncheackedInvoice(int userId) {
            return base.Channel.getUncheackedInvoice(userId);
        }
        
        public System.Threading.Tasks.Task<int> getUncheackedInvoiceAsync(int userId) {
            return base.Channel.getUncheackedInvoiceAsync(userId);
        }
        
        public bool checkout(int invoiceId) {
            return base.Channel.checkout(invoiceId);
        }
        
        public System.Threading.Tasks.Task<bool> checkoutAsync(int invoiceId) {
            return base.Channel.checkoutAsync(invoiceId);
        }
        
        public GG_WebStore.ServiceReference1.InvoiceLine[] getProductsOnInvoice(int invoiceId) {
            return base.Channel.getProductsOnInvoice(invoiceId);
        }
        
        public System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.InvoiceLine[]> getProductsOnInvoiceAsync(int invoiceId) {
            return base.Channel.getProductsOnInvoiceAsync(invoiceId);
        }
        
        public bool updateCart(int invoiceId, int productId, int quantity) {
            return base.Channel.updateCart(invoiceId, productId, quantity);
        }
        
        public System.Threading.Tasks.Task<bool> updateCartAsync(int invoiceId, int productId, int quantity) {
            return base.Channel.updateCartAsync(invoiceId, productId, quantity);
        }
        
        public GG_WebStore.ServiceReference1.Product[] getAllProducts() {
            return base.Channel.getAllProducts();
        }
        
        public System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.Product[]> getAllProductsAsync() {
            return base.Channel.getAllProductsAsync();
        }
        
        public GG_WebStore.ServiceReference1.Product GetSingleProduct(int ID) {
            return base.Channel.GetSingleProduct(ID);
        }
        
        public System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.Product> GetSingleProductAsync(int ID) {
            return base.Channel.GetSingleProductAsync(ID);
        }
        
        public GG_WebStore.ServiceReference1.User getUser(string Email) {
            return base.Channel.getUser(Email);
        }
        
        public System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.User> getUserAsync(string Email) {
            return base.Channel.getUserAsync(Email);
        }
        
        public GG_WebStore.ServiceReference1.Product[] getNewArrivalProducts() {
            return base.Channel.getNewArrivalProducts();
        }
        
        public System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.Product[]> getNewArrivalProductsAsync() {
            return base.Channel.getNewArrivalProductsAsync();
        }
        
        public GG_WebStore.ServiceReference1.Product[] getFeaturedProducts() {
            return base.Channel.getFeaturedProducts();
        }
        
        public System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.Product[]> getFeaturedProductsAsync() {
            return base.Channel.getFeaturedProductsAsync();
        }
        
        public int countProducts() {
            return base.Channel.countProducts();
        }
        
        public System.Threading.Tasks.Task<int> countProductsAsync() {
            return base.Channel.countProductsAsync();
        }
        
        public int GenerateUserRegReport(System.DateTime regfordate) {
            return base.Channel.GenerateUserRegReport(regfordate);
        }
        
        public System.Threading.Tasks.Task<int> GenerateUserRegReportAsync(System.DateTime regfordate) {
            return base.Channel.GenerateUserRegReportAsync(regfordate);
        }
        
        public bool DeleteProductById(int productId) {
            return base.Channel.DeleteProductById(productId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteProductByIdAsync(int productId) {
            return base.Channel.DeleteProductByIdAsync(productId);
        }
        
        public bool EditProduct(int productId, string productName, int prodcuctActive, decimal productPrice, string productImage, decimal productDiscount, int CategoryId, string productDescri, int brandId, int productStock) {
            return base.Channel.EditProduct(productId, productName, prodcuctActive, productPrice, productImage, productDiscount, CategoryId, productDescri, brandId, productStock);
        }
        
        public System.Threading.Tasks.Task<bool> EditProductAsync(int productId, string productName, int prodcuctActive, decimal productPrice, string productImage, decimal productDiscount, int CategoryId, string productDescri, int brandId, int productStock) {
            return base.Channel.EditProductAsync(productId, productName, prodcuctActive, productPrice, productImage, productDiscount, CategoryId, productDescri, brandId, productStock);
        }
        
        public bool AddProduct(string productName, int prodcuctActive, decimal productPrice, string productImage, decimal productDiscount, int CategoryId, string productDescri, int brandId, int productStock) {
            return base.Channel.AddProduct(productName, prodcuctActive, productPrice, productImage, productDiscount, CategoryId, productDescri, brandId, productStock);
        }
        
        public System.Threading.Tasks.Task<bool> AddProductAsync(string productName, int prodcuctActive, decimal productPrice, string productImage, decimal productDiscount, int CategoryId, string productDescri, int brandId, int productStock) {
            return base.Channel.AddProductAsync(productName, prodcuctActive, productPrice, productImage, productDiscount, CategoryId, productDescri, brandId, productStock);
        }
        
        public GG_WebStore.ServiceReference1.Product[] GetProductsByPriceRange(decimal minimumPrice, decimal maximumPrice) {
            return base.Channel.GetProductsByPriceRange(minimumPrice, maximumPrice);
        }
        
        public System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.Product[]> GetProductsByPriceRangeAsync(decimal minimumPrice, decimal maximumPrice) {
            return base.Channel.GetProductsByPriceRangeAsync(minimumPrice, maximumPrice);
        }
        
        public GG_WebStore.ServiceReference1.Product[] GetProductByBrand(string name) {
            return base.Channel.GetProductByBrand(name);
        }
        
        public System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.Product[]> GetProductByBrandAsync(string name) {
            return base.Channel.GetProductByBrandAsync(name);
        }
        
        public GG_WebStore.ServiceReference1.Product[] GetProductByCategory(string name) {
            return base.Channel.GetProductByCategory(name);
        }
        
        public System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.Product[]> GetProductByCategoryAsync(string name) {
            return base.Channel.GetProductByCategoryAsync(name);
        }
        
        public GG_WebStore.ServiceReference1.InvoiceLineStruct[] GetInvoiceLines(int InvoiceId) {
            return base.Channel.GetInvoiceLines(InvoiceId);
        }
        
        public System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.InvoiceLineStruct[]> GetInvoiceLinesAsync(int InvoiceId) {
            return base.Channel.GetInvoiceLinesAsync(InvoiceId);
        }
        
        public GG_WebStore.ServiceReference1.Invoice[] GetInvoices(int UserId) {
            return base.Channel.GetInvoices(UserId);
        }
        
        public System.Threading.Tasks.Task<GG_WebStore.ServiceReference1.Invoice[]> GetInvoicesAsync(int UserId) {
            return base.Channel.GetInvoicesAsync(UserId);
        }
    }
}
